### PR TITLE
Add support for OSX

### PR DESCRIPTION
**Pull request by jpereira**

### CODE REVIEW

**Comment by jpereira** [comment]
Hi @rgl ,

Please find below some evidence about the new capability.

1. Build

```
[jpereira@jorge-sugarloaf:packer-provisioner-windows-update.git]$ make
cd update && go run assets_generate.go
writing assets_vfsdata.go
GOOS=linux GOARCH=amd64 go build -v -o packer-provisioner-windows-update
github.com/rgl/packer-provisioner-windows-update/update
github.com/rgl/packer-provisioner-windows-update
GOOS=windows GOARCH=amd64 go build -v -o packer-provisioner-windows-update.exe
github.com/rgl/packer-provisioner-windows-update/update
github.com/rgl/packer-provisioner-windows-update
GOOS=darwin GOARCH=amd64 go build -v -o packer-provisioner-windows-update.osx
github.com/rgl/packer-provisioner-windows-update/update
github.com/rgl/packer-provisioner-windows-update
[jpereira@jorge-sugarloaf:packer-provisioner-windows-update.git]$
```

2. Packages

```
[jpereira@jorge-sugarloaf:packer-provisioner-windows-update.git]$ make package
tar -czf packer-provisioner-windows-update-linux.tgz packer-provisioner-windows-update
zip packer-provisioner-windows-update-windows.zip packer-provisioner-windows-update.exe
  adding: packer-provisioner-windows-update.exe (deflated 56%)
(mkdir -p tmp && cd tmp/ && cp ../packer-provisioner-windows-update.osx packer-provisioner-windows-update && \
	tar -czf ../packer-provisioner-windows-update-osx.tgz packer-provisioner-windows-update)
[jpereira@jorge-sugarloaf:packer-provisioner-windows-update.git]$ ls -l *.tgz
-rw-r--r--  1 jpereira  staff  14006280 Jul 20 16:26 packer-provisioner-windows-update-linux.tgz
-rw-r--r--  1 jpereira  staff  13914522 Jul 20 16:26 packer-provisioner-windows-update-osx.tgz
[jpereira@jorge-sugarloaf:packer-provisioner-windows-update.git]$ ls -l *.tgz *.exe
-rw-r--r--  1 jpereira  staff  14006280 Jul 20 16:26 packer-provisioner-windows-update-linux.tgz
-rw-r--r--  1 jpereira  staff  13914522 Jul 20 16:26 packer-provisioner-windows-update-osx.tgz
-rwxr-xr-x  1 jpereira  staff  31643648 Jul 20 16:25 packer-provisioner-windows-update.exe
[jpereira@jorge-sugarloaf:packer-provisioner-windows-update.git]$
```

**Comment by jpereira** [comment]
I've built the windows-2019-amd64-virtualbox.box as well on OSX as can be seen [here](https://pastebin.com/F1fp6ELG).

**Comment by rgl** [comment]
Looking good!

Before merging, can you please make a couple of changes?

Change the word `osx` to `darwin` (the value of the `GOOS` environment variable) to make it similar to what go does (e.g. `https://golang.org/dl/go1.14.6.darwin-amd64.pkg`).

Instead of using the extension `.osx` in the binary use `-darwin`, e.g. the binary would be called `packer-provisioner-windows-update-darwin`. Or even better, instead of putting the binaries in the current directory, put them inside `build/$GOOS` (e.g. `build/darwin/packer-provisioner-windows-update`).

**Comment by jpereira** [comment]
For sure. even I did some extra improvements to reduce the Makefile and simplify. (think so)

1. Building.

```
[jpereira@jorge-sugarloaf:packer-provisioner-windows-update.git]$ make build
UPDATE update/assets_vfsdata.go
writing assets_vfsdata.go
BUILD build/linux/packer-provisioner-windows-update
github.com/rgl/packer-provisioner-windows-update/update
github.com/rgl/packer-provisioner-windows-update
BUILD build/windows/packer-provisioner-windows-update.exe
github.com/rgl/packer-provisioner-windows-update/update
github.com/rgl/packer-provisioner-windows-update
BUILD build/darwin/packer-provisioner-windows-update
github.com/rgl/packer-provisioner-windows-update/update
github.com/rgl/packer-provisioner-windows-update
```

2. Generated binaries under `build/$(GOOS)/packer-provisioner-windows`

```
[jpereira@jorge-sugarloaf:packer-provisioner-windows-update.git]$ find build -type f
build/linux/packer-provisioner-windows-update
build/darwin/packer-provisioner-windows-update
build/windows/packer-provisioner-windows-update.exe
[jpereira@jorge-sugarloaf:packer-provisioner-windows-update.git]$
```

3. Generating deploy packages appending the `$(ARCH)` as your mentioned `.pkg` link.

```
[jpereira@jorge-sugarloaf:packer-provisioner-windows-update.git]$ make package
(cd build/linux  && tar -czf ../../packer-provisioner-windows-update_linux-amd64.tgz packer-provisioner-windows-update)
(cd build/darwin && tar -czf ../../packer-provisioner-windows-update_darwin-amd64.tgz packer-provisioner-windows-update)
(cd build/windows && zip ../../packer-provisioner-windows-update_windows-amd64.zip packer-provisioner-windows-update.exe)
  adding: packer-provisioner-windows-update.exe (deflated 56%)
[jpereira@jorge-sugarloaf:packer-provisioner-windows-update.git]$ ls -l packer-provisioner-windows-update_*
-rw-r--r--  1 jpereira  staff  13914519 Jul 21 16:59 packer-provisioner-windows-update_darwin-amd64.tgz
-rw-r--r--  1 jpereira  staff  14006283 Jul 21 16:59 packer-provisioner-windows-update_linux-amd64.tgz
-rw-r--r--  1 jpereira  staff  13796809 Jul 21 17:00 packer-provisioner-windows-update_windows-amd64.zip
[jpereira@jorge-sugarloaf:packer-provisioner-windows-update.git]$
```

**Comment by rgl** [comment]
Thank you! I'll just simplify it a bit and still use the same zip file name as packer-provisioner-windows-update-windows.zip instead of packer-provisioner-windows-update_windows-amd64.zip.

**Comment by rgl** [comment]
I've added an GitHub workflow at https://github.com/rgl/packer-provisioner-windows-update/actions?query=workflow%3ABuild. Can you try the generated binaries to see if they work in your mac?

**Comment by jpereira** [comment]
Hi @rgl ,

It's working as well.

```
[jpereira@jorge-sugarloaf:packer-provisioner-windows-update.git]$ make
cd update && go run assets_generate.go
writing assets_vfsdata.go
mkdir -p build/darwin/
GOOS=darwin GOARCH=amd64 go build -v -o build/darwin/packer-provisioner-windows-update
github.com/rgl/packer-provisioner-windows-update/update
github.com/rgl/packer-provisioner-windows-update
mkdir -p build/linux/
GOOS=linux GOARCH=amd64 go build -v -o build/linux/packer-provisioner-windows-update
github.com/rgl/packer-provisioner-windows-update/update
github.com/rgl/packer-provisioner-windows-update
mkdir -p build/windows/
GOOS=windows GOARCH=amd64 go build -v -o build/windows/packer-provisioner-windows-update.exe
github.com/rgl/packer-provisioner-windows-update/update
github.com/rgl/packer-provisioner-windows-update
[jpereira@jorge-sugarloaf:packer-provisioner-windows-update.git]$ make package
cd build/darwin && tar -czf ../../packer-provisioner-windows-update-darwin.tgz packer-provisioner-windows-update
cd build/linux && tar -czf ../../packer-provisioner-windows-update-linux.tgz packer-provisioner-windows-update
cd build/windows && zip ../../packer-provisioner-windows-update-windows.zip packer-provisioner-windows-update.exe
  adding: packer-provisioner-windows-update.exe (deflated 56%)
[jpereira@jorge-sugarloaf:packer-provisioner-windows-update.git]$ ls -l packer-provisioner-windows-update-*
-rw-r--r--  1 jpereira  staff  13914527 Jul 22 09:41 packer-provisioner-windows-update-darwin.tgz
-rw-r--r--  1 jpereira  staff  14006286 Jul 22 09:41 packer-provisioner-windows-update-linux.tgz
-rw-r--r--  1 jpereira  staff  13796807 Jul 22 09:41 packer-provisioner-windows-update-windows.zip
[jpereira@jorge-sugarloaf:packer-provisioner-windows-update.git]$
```

Obrigado!

**Pull request merged**
