### PR TITLE
Feature/priority level for 2008r2

### PR DESCRIPTION
**Pull request by bishopbm1**
Fixed issue where when provisioning to servers older then Windows 2012 the download priority causes error: 
```
vsphere-iso: ERROR: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
    vsphere-iso: ERROR: at <ScriptBlock>, C:\Windows\Temp\packer-windows-update.ps1: line 195
    vsphere-iso: ERROR: at <ScriptBlock>, <No file>: line 1
    vsphere-iso: ERROR EXCEPTION: System.ArgumentException: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
```
Found that on older versions of Windows the highest priority level was 3 instead of 4. Adding an if for server versions fixed the issue. 

Successfully updated OS's: Windows Server 2008 R2, Windows Server 2012 R2, Windows Server 2016

### CODE REVIEW

**Comment by tvories** [comment]
Excellent work!  I'm looking forward to being able to use this when it's merged.

**Comment by rgl** [comment]
Thanks for PR!

Can you guys please test the artifacts from https://ci.appveyor.com/project/rgl/packer-provisioner-windows-update/builds/20742691/artifacts and let me known if they work?

**Comment by bishopbm1** [comment]
@rgl I tested both the windows and the linux artifact and they both worked as expected on OS's: Windows Server 2008 R2, Windows Server 2012 R2, Windows Server 2016

**Comment by tvories** [comment]
Any reason this isn't being merged?

**Comment by rgl** [comment]
release is now available at https://github.com/rgl/packer-provisioner-windows-update/releases/tag/v0.6.1

**Pull request merged**
