### PR TITLE
Updated Mac Support

### PR DESCRIPTION
**Pull request by tryfan**
The other PR is a little old at this point, and I just made this for an update.

### CODE REVIEW

**Comment by jpereira** [comment]
+1

**Comment by rgl** [comment]
Having a `.mac` extension means that we have to rename the file from `packer-provisioner-windows-update.mac` to ` packer-provisioner-windows-update` before we can use it? If so, it would be better to put the mac version inside a sub-directory and create the binary as `build/mac/packer-provisioner-windows-update`.

Disclaimer: I do not have a mac to try this on.

**Comment by jpereira** [comment]
Come on @rgl! Let's make that happening! :)

**Comment by jpereira** [comment]
Probably it was obsoleted by #71

**Comment by rgl** [comment]
Thank you! I ended up using #71.

**Pull request closed without merging**
