### PR TITLE
Retry update search on failure

### PR DESCRIPTION
**Pull request by george-richardson**
I have been having an issue updating a Windows 2012 machine where occasionally searching for updates will fail with the following packer output:

```
vmware-iso: Searching for Windows updates...
vmware-iso: ERROR: Exception has been thrown by the target of an invocation.
vmware-iso: ERROR: at <ScriptBlock>, C:\Windows\Temp\packer-windows-update.ps1: line 157
vmware-iso: ERROR: at <ScriptBlock>, <No file>: line 1
vmware-iso: ERROR EXCEPTION: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x80072EFE
vmware-iso: ERROR EXCEPTION:    --- End of inner exception stack trace ---
vmware-iso: ERROR EXCEPTION:    at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
vmware-iso: ERROR EXCEPTION:    at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
vmware-iso: ERROR EXCEPTION:    at System.Management.Automation.ComMethod.InvokeMethod(PSMethod method, Object[] arguments)
```

This fix will retry the search if an exception is raised or if the COM result is not 2. With it in place I get output similar to the following when an error is produced:
```
vmware-iso: Running Windows update...
vmware-iso: Searching for Windows updates...
vmware-iso: Search for Windows updates failed with 'Exception calling "Search" with "1" argument(s): "Exception from HRESULT: 0x80072EFE"'. Retrying...
vmware-iso: Search for Windows updates failed with 'Exception calling "Search" with "1" argument(s): "Exception from HRESULT: 0x80072EFE"'. Retrying...
vmware-iso: Found Windows update (2013-10-17; 9.65 MB): Update for Windows Server 2012 R2 (KB2884846)
vmware-iso: Found Windows update (2013-12-10; 0.49 MB): Security Update for Windows Server 2012 R2 (KB2892074)
vmware-iso: Found Windows update (2014-02-11; 35.26 MB): Security Update for Microsoft .NET Framework 4.5.1 on Windows 8.1 and Windows Server 2012 R2 for x64-based Systems (KB2898871)
```
The actual error produced `0x80072EFE` seems to be issues with connectivity to the update service but it always fixes itself after one or two retries. I think perhaps this could be due to a required service still starting in the background in 2012 but that's just a guess. Either way it's not a problem with your tool.

I've tried to keep the code style as close to yours as possible but let me know if you want anything changed.

### CODE REVIEW

**Comment by rgl** [comment]
Thanks!

**Comment by george-richardson** [comment]
Thanks for the quick turnaround!

**Comment by george-richardson** [comment]
@rgl Do you know when you are next going to make a chocolatey release? I'd like to switch back to using your binaries on my build agents.

**Comment by george-richardson** [comment]
Hi @rgl don't wish to annoy you but have you put some thought into the above question?

**Comment by rgl** [comment]
sorry for the delay... its at https://github.com/rgl/packer-provisioner-windows-update/releases/tag/v0.7.0

**Comment by george-richardson** [comment]
Amazing, thanks a lot!

**Pull request merged**
